---
title: "Feb. 02"
output: html_document
date: "2023-02-03"
---
## combine hr, bp, rsp and filling all missing data with spline interpolation

```{r}
id_bp = unique(bp_cleaned$id)
id_hr = unique(hr_cleaned$id)
id_rsp = unique(rsp_cleaned$id)

comb_df = left_join((hr_cleaned  %>% filter(id %in% id_bp)), bp_cleaned, by = c("id", "period", "interval", "condition")) %>%
  mutate(interval = as.numeric(interval)) %>%
  select(-diff.x, -diff.y)

comb_df$period <- factor(comb_df$period, levels=c('1','2','3','4','5','6','7','8','9','10','11','12','CP','DBT','SST','ST','C3'))

comb_df = left_join((comb_df %>% filter(id %in% id_rsp)), rsp_cleaned, by = c("id", "period", "interval", "condition"))  %>% 
  mutate(period = as.factor(period)) %>%
  arrange(id, period, interval) %>%
  select(-diff) %>% 
  filter(period == '1'|period == '2'|period == '3'|period == '4'|period == '5'|period == '6'|period == '7'|period == '8'|period == '9'|period == '10'|period == '11'|period == '12')

## keep only period 1-12 and remove id with all missing values in rsp rate
comb_df = comb_df[!duplicated(comb_df[c(1,2,3)]),] %>% filter(id != "mi058")

# statsNA(comb_df$rate)
levels(comb_df$period)
unique(comb_df$id)
```


```{r}
j = 1
for (i in 1:length(unique(comb_df$id))) {
  
  cur_id = as.character(unique(comb_df$id)[i])
  cur = comb_df %>% filter(id == cur_id)
  
  cur_rate_mean = na_interpolation(cur$rate_mean, option = "spline")
  cur_pval_mean = na_interpolation(cur$pval_mean, option = "spline")
  cur_pval_rsp = na_interpolation(cur$pVal, option = "spline")
  cur_rate_rsp = na_interpolation(cur$rate, option = "spline")
 
  comb_df$rate_mean[j:(length(cur_pval_mean)+j-1)] = cur_rate_mean
  comb_df$pval_mean[j:(length(cur_pval_mean)+j-1)] = cur_pval_mean
  comb_df$pVal[j:(length(cur_pval_mean)+j-1)] = cur_pval_rsp
  comb_df$rate[j:(length(cur_pval_mean)+j-1)] = cur_rate_rsp
  
  j = j + length(cur_pval_mean)
}

comb_df = comb_df %>% group_by(id, period) %>%
  mutate(rate_diff = rate_mean - lag(rate_mean),
         pval_diff = pval_mean - lag(pval_mean),
         pval_rsp_diff = pVal - lag(pVal),
         rate_rsp_diff = rate - lag(rate)) %>%
  rename(rate_hr = rate_mean, rate_hr_diff = rate_diff,
         pval_bp = pval_mean, pval_bp_diff = pval_diff,
         pval_rsp = pVal, rate_rsp = rate) %>%
  mutate(period = as.numeric(period)) %>%
  mutate(interval = as.integer(interval)) %>% drop_na()

```

## period combination and period define

### Base (period 1)

```{r}
base_df = comb_df %>% filter(period == 1) %>% arrange(id, period, interval)

base_control = base_df %>% filter(condition == "control") 
base_13 = base_df %>% filter(condition == "Mutation") 
base_2 = base_df %>% filter(condition == "Deletion") 
```

### pre (period 2)

```{r}
pre_df = comb_df %>% filter(period == 2) %>% arrange(id, period, interval)

pre_control = pre_df %>% filter(condition == "control") 
pre_13 = pre_df %>% filter(condition == "Mutation") 
pre_2 = pre_df %>% filter(condition == "Deletion") 
```


### Task (period 3-5)

```{r}
task_df = comb_df %>% filter(period == 3|period == 4|period == 5) %>% arrange(id, period, interval)

task_control = task_df %>% filter(condition == "control")
task_13 = task_df %>% filter(condition == "Mutation") 
task_2 = task_df %>% filter(condition == "Deletion") 
```

### post (period 6-12)

```{r}
post_df = comb_df %>% filter(period == 6|period == 7|period == 8|period == 9|period == 10|period == 11|period == 12) %>% arrange(id, period, interval)

post_control = post_df %>% filter(condition == "control") 
post_13 = post_df %>% filter(condition == "Mutation") 
post_2 = post_df %>% filter(condition == "Deletion") 
```

### Overall (Period 1-12)

```{r}
all_df = comb_df %>% arrange(id, period, interval)
  
all_control = all_df %>% filter(condition == "control") 
all_13 = all_df %>% filter(condition == "Mutation") 
all_2 = all_df %>% filter(condition == "Deletion") 
```


## use lag difference

* a: hr to bp, b: bp to hr
* c: hr to rsp, d: rsp to hr
* e: bp to rsp, f: rsp to bp

### Base (period 1)
```{r}
unique(base_control$id)
sum_p1 = base_control %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_base_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_base_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_base_lag_control)) {
  
   cur_id = as.character(trans_res_base_lag_control[i,1])
   cur = base_control %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff, type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff, type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff, type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_base_lag_control$a[i] = TE1$coef[1, 1]
   trans_res_base_lag_control$b[i] = TE1$coef[2, 1]
   trans_res_base_lag_control$c[i] = TE2$coef[1, 1]
   trans_res_base_lag_control$d[i] = TE2$coef[2, 1]
   trans_res_base_lag_control$e[i] = TE3$coef[1, 1]
   trans_res_base_lag_control$f[i] = TE3$coef[2, 1]
}

## group 13
unique(base_13$id)
sum_p1 = base_13 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_base_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_base_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_base_lag_13)) {
  
   cur_id = as.character(trans_res_base_lag_13[i,1])
   cur = base_13 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_base_lag_13$a[i] = TE1$coef[1, 1]
   trans_res_base_lag_13$b[i] = TE1$coef[2, 1]
   trans_res_base_lag_13$c[i] = TE2$coef[1, 1]
   trans_res_base_lag_13$d[i] = TE2$coef[2, 1]
   trans_res_base_lag_13$e[i] = TE3$coef[1, 1]
   trans_res_base_lag_13$f[i] = TE3$coef[2, 1]
}


## group 2
unique(base_2$id)
sum_p1 = base_2 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_base_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_base_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_base_lag_2)) {
  
   cur_id = as.character(trans_res_base_lag_2[i,1])
   cur = base_2 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_base_lag_2$a[i] = TE1$coef[1, 1]
   trans_res_base_lag_2$b[i] = TE1$coef[2, 1]
   trans_res_base_lag_2$c[i] = TE2$coef[1, 1]
   trans_res_base_lag_2$d[i] = TE2$coef[2, 1]
   trans_res_base_lag_2$e[i] = TE3$coef[1, 1]
   trans_res_base_lag_2$f[i] = TE3$coef[2, 1]
}

```


### Pre (period2)

```{r}
unique(pre_control$id)
sum_p1 = pre_control %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_pre_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_pre_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_pre_lag_control)) {
  
   cur_id = as.character(trans_res_pre_lag_control[i,1])
   cur = pre_control %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_pre_lag_control$a[i] = TE1$coef[1, 1]
   trans_res_pre_lag_control$b[i] = TE1$coef[2, 1]
   trans_res_pre_lag_control$c[i] = TE2$coef[1, 1]
   trans_res_pre_lag_control$d[i] = TE2$coef[2, 1]
   trans_res_pre_lag_control$e[i] = TE3$coef[1, 1]
   trans_res_pre_lag_control$f[i] = TE3$coef[2, 1]
}

## group 13
unique(pre_13$id)
sum_p1 = pre_13 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_pre_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_pre_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_pre_lag_13)) {
  
   cur_id = as.character(trans_res_pre_lag_13[i,1])
   cur = pre_13 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_pre_lag_13$a[i] = TE1$coef[1, 1]
   trans_res_pre_lag_13$b[i] = TE1$coef[2, 1]
   trans_res_pre_lag_13$c[i] = TE2$coef[1, 1]
   trans_res_pre_lag_13$d[i] = TE2$coef[2, 1]
   trans_res_pre_lag_13$e[i] = TE3$coef[1, 1]
   trans_res_pre_lag_13$f[i] = TE3$coef[2, 1]
}


## group 2
unique(pre_2$id)
sum_p1 = pre_2 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_pre_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_pre_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_pre_lag_2)) {
  
   cur_id = as.character(trans_res_pre_lag_2[i,1])
   cur = pre_2 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_pre_lag_2$a[i] = TE1$coef[1, 1]
   trans_res_pre_lag_2$b[i] = TE1$coef[2, 1]
   trans_res_pre_lag_2$c[i] = TE2$coef[1, 1]
   trans_res_pre_lag_2$d[i] = TE2$coef[2, 1]
   trans_res_pre_lag_2$e[i] = TE3$coef[1, 1]
   trans_res_pre_lag_2$f[i] = TE3$coef[2, 1]
}

```


### Task (period 3-5)

```{r}
unique(task_control$id)
sum_p1 = task_control %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_task_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_task_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_task_lag_control)) {
  
   cur_id = as.character(trans_res_task_lag_control[i,1])
   cur = task_control %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_task_lag_control$a[i] = TE1$coef[1, 1]
   trans_res_task_lag_control$b[i] = TE1$coef[2, 1]
   trans_res_task_lag_control$c[i] = TE2$coef[1, 1]
   trans_res_task_lag_control$d[i] = TE2$coef[2, 1]
   trans_res_task_lag_control$e[i] = TE3$coef[1, 1]
   trans_res_task_lag_control$f[i] = TE3$coef[2, 1]
}

## group 13
unique(task_13$id)
sum_p1 = task_13 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_task_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_task_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_task_lag_13)) {
  
   cur_id = as.character(trans_res_task_lag_13[i,1])
   cur = task_13 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_task_lag_13$a[i] = TE1$coef[1, 1]
   trans_res_task_lag_13$b[i] = TE1$coef[2, 1]
   trans_res_task_lag_13$c[i] = TE2$coef[1, 1]
   trans_res_task_lag_13$d[i] = TE2$coef[2, 1]
   trans_res_task_lag_13$e[i] = TE3$coef[1, 1]
   trans_res_task_lag_13$f[i] = TE3$coef[2, 1]
}


## group 2
unique(task_2$id)
sum_p1 = task_2 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_task_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_task_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_task_lag_2)) {
  
   cur_id = as.character(trans_res_task_lag_2[i,1])
   cur = task_2 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_task_lag_2$a[i] = TE1$coef[1, 1]
   trans_res_task_lag_2$b[i] = TE1$coef[2, 1]
   trans_res_task_lag_2$c[i] = TE2$coef[1, 1]
   trans_res_task_lag_2$d[i] = TE2$coef[2, 1]
   trans_res_task_lag_2$e[i] = TE3$coef[1, 1]
   trans_res_task_lag_2$f[i] = TE3$coef[2, 1]
}

```


### Post (period 6-12)

```{r}
unique(post_control$id)
sum_p1 = post_control %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_post_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_post_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_post_lag_control)) {
  
   cur_id = as.character(trans_res_post_lag_control[i,1])
   cur = post_control %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_post_lag_control$a[i] = TE1$coef[1, 1]
   trans_res_post_lag_control$b[i] = TE1$coef[2, 1]
   trans_res_post_lag_control$c[i] = TE2$coef[1, 1]
   trans_res_post_lag_control$d[i] = TE2$coef[2, 1]
   trans_res_post_lag_control$e[i] = TE3$coef[1, 1]
   trans_res_post_lag_control$f[i] = TE3$coef[2, 1]
}

## group 13
unique(post_13$id)
sum_p1 = post_13 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_post_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_post_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_post_lag_13)) {
  
   cur_id = as.character(trans_res_post_lag_13[i,1])
   cur = post_13 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_post_lag_13$a[i] = TE1$coef[1, 1]
   trans_res_post_lag_13$b[i] = TE1$coef[2, 1]
   trans_res_post_lag_13$c[i] = TE2$coef[1, 1]
   trans_res_post_lag_13$d[i] = TE2$coef[2, 1]
   trans_res_post_lag_13$e[i] = TE3$coef[1, 1]
   trans_res_post_lag_13$f[i] = TE3$coef[2, 1]
}


## group 2
unique(post_2$id)
sum_p1 = post_2 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_post_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_post_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_post_lag_2)) {
  
   cur_id = as.character(trans_res_post_lag_2[i,1])
   cur = post_2 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_post_lag_2$a[i] = TE1$coef[1, 1]
   trans_res_post_lag_2$b[i] = TE1$coef[2, 1]
   trans_res_post_lag_2$c[i] = TE2$coef[1, 1]
   trans_res_post_lag_2$d[i] = TE2$coef[2, 1]
   trans_res_post_lag_2$e[i] = TE3$coef[1, 1]
   trans_res_post_lag_2$f[i] = TE3$coef[2, 1]
}

```


### Overall

```{r}
unique(all_control$id)
sum_p1 = all_control %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_all_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_all_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_all_lag_control)) {
  
   cur_id = as.character(trans_res_all_lag_control[i,1])
   cur = all_control %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_all_lag_control$a[i] = TE1$coef[1, 1]
   trans_res_all_lag_control$b[i] = TE1$coef[2, 1]
   trans_res_all_lag_control$c[i] = TE2$coef[1, 1]
   trans_res_all_lag_control$d[i] = TE2$coef[2, 1]
   trans_res_all_lag_control$e[i] = TE3$coef[1, 1]
   trans_res_all_lag_control$f[i] = TE3$coef[2, 1]
}

## group 13
unique(all_13$id)
sum_p1 = all_13 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_all_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_all_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_all_lag_13)) {
  
   cur_id = as.character(trans_res_all_lag_13[i,1])
   cur = all_13 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_all_lag_13$a[i] = TE1$coef[1, 1]
   trans_res_all_lag_13$b[i] = TE1$coef[2, 1]
   trans_res_all_lag_13$c[i] = TE2$coef[1, 1]
   trans_res_all_lag_13$d[i] = TE2$coef[2, 1]
   trans_res_all_lag_13$e[i] = TE3$coef[1, 1]
   trans_res_all_lag_13$f[i] = TE3$coef[2, 1]
}


## group 2
unique(all_2$id)
sum_p1 = all_2 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_all_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_all_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_all_lag_2)) {
  
   cur_id = as.character(trans_res_all_lag_2[i,1])
   cur = all_2 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_all_lag_2$a[i] = TE1$coef[1, 1]
   trans_res_all_lag_2$b[i] = TE1$coef[2, 1]
   trans_res_all_lag_2$c[i] = TE2$coef[1, 1]
   trans_res_all_lag_2$d[i] = TE2$coef[2, 1]
   trans_res_all_lag_2$e[i] = TE3$coef[1, 1]
   trans_res_all_lag_2$f[i] = TE3$coef[2, 1]
}

```


## Ice task

```{r}
id_bp = unique(bp_cleaned$id)
id_hr = unique(hr_cleaned$id)
id_rsp = unique(rsp_cleaned$id)

comb_df = left_join((hr_cleaned  %>% filter(id %in% id_bp)), bp_cleaned, by = c("id", "period", "interval", "condition")) %>%
  mutate(interval = as.numeric(interval)) %>%
  select(-diff.x, -diff.y)

comb_df$period <- factor(comb_df$period, levels=c('1','2','3','4','5','6','7','8','9','10','11','12','CP','DBT','SST','ST','C3'))

comb_df = left_join((comb_df %>% filter(id %in% id_rsp)), rsp_cleaned, by = c("id", "period", "interval", "condition"))  %>% 
  mutate(period = as.factor(period)) %>%
  arrange(id, period, interval) %>%
  select(-diff) %>% 
  filter(period %in% c('DBT', 'ST', 'SST', 'CP'))

## keep only period 1-12 and remove id with all missing values in rsp rate
comb_df = comb_df[!duplicated(comb_df[c(1,2,3)]),] %>% filter(id != "mi012"& id != "mi030"& id != "mi058")

# statsNA(comb_df$rate)
unique(comb_df$period)
unique(comb_df$id)

j = 1
for (i in 1:length(unique(comb_df$id))) {
  
  cur_id = as.character(unique(comb_df$id)[i])
  cur = comb_df %>% filter(id == cur_id)
  
  cur_rate_mean = na_interpolation(cur$rate_mean, option = "spline")
  cur_pval_mean = na_interpolation(cur$pval_mean, option = "spline")
  cur_pval_rsp = na_interpolation(cur$pVal, option = "spline")
  cur_rate_rsp = na_interpolation(cur$rate, option = "spline")
 
  comb_df$rate_mean[j:(length(cur_pval_mean)+j-1)] = cur_rate_mean
  comb_df$pval_mean[j:(length(cur_pval_mean)+j-1)] = cur_pval_mean
  comb_df$pVal[j:(length(cur_pval_mean)+j-1)] = cur_pval_rsp
  comb_df$rate[j:(length(cur_pval_mean)+j-1)] = cur_rate_rsp
  
  j = j + length(cur_pval_mean)
}

comb_df = comb_df %>% group_by(id, period) %>%
  mutate(rate_diff = rate_mean - lag(rate_mean),
         pval_diff = pval_mean - lag(pval_mean),
         pval_rsp_diff = pVal - lag(pVal),
         rate_rsp_diff = rate - lag(rate)) %>%
  rename(rate_hr = rate_mean, rate_hr_diff = rate_diff,
         pval_bp = pval_mean, pval_bp_diff = pval_diff,
         pval_rsp = pVal, rate_rsp = rate) %>%
  mutate(interval = as.integer(interval)) %>% drop_na()

dbt_df = comb_df  %>% arrange(id, period, interval)
dbt_control = dbt_df %>% filter(condition == "control") 
dbt_13 = dbt_df %>% filter(condition == "Mutation") 
dbt_2 = dbt_df %>% filter(condition == "Deletion") 
```

#### TE compute
```{r}
unique(dbt_control$id)
sum_p1 = dbt_control %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_dbt_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_dbt_lag_control = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_dbt_lag_control)) {
  
   cur_id = as.character(trans_res_dbt_lag_control[i,1])
   cur = dbt_control %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff, type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff, type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff, type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_dbt_lag_control$a[i] = TE1$coef[1, 1]
   trans_res_dbt_lag_control$b[i] = TE1$coef[2, 1]
   trans_res_dbt_lag_control$c[i] = TE2$coef[1, 1]
   trans_res_dbt_lag_control$d[i] = TE2$coef[2, 1]
   trans_res_dbt_lag_control$e[i] = TE3$coef[1, 1]
   trans_res_dbt_lag_control$f[i] = TE3$coef[2, 1]
}

## group 13
unique(dbt_13$id)
sum_p1 = dbt_13 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_dbt_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_dbt_lag_13 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_dbt_lag_13)) {
  
   cur_id = as.character(trans_res_dbt_lag_13[i,1])
   cur = dbt_13 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_dbt_lag_13$a[i] = TE1$coef[1, 1]
   trans_res_dbt_lag_13$b[i] = TE1$coef[2, 1]
   trans_res_dbt_lag_13$c[i] = TE2$coef[1, 1]
   trans_res_dbt_lag_13$d[i] = TE2$coef[2, 1]
   trans_res_dbt_lag_13$e[i] = TE3$coef[1, 1]
   trans_res_dbt_lag_13$f[i] = TE3$coef[2, 1]
}


## group 2
unique(dbt_2$id)
sum_p1 = dbt_2 %>% group_by(id) %>% summarize(num_obs = n()) 

trans_res_dbt_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)
trans_sig_dbt_lag_2 = sum_p1 %>% select(id, num_obs) %>% mutate(a = NA, b = NA, c = NA, d = NA, e = NA, f = NA)

i = 1
for (i in 1:nrow(trans_res_dbt_lag_2)) {
  
   cur_id = as.character(trans_res_dbt_lag_2[i,1])
   cur = dbt_2 %>% filter(id == cur_id)
   
   TE1 = transfer_entropy(cur$rate_hr_diff, cur$pval_bp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE2 = transfer_entropy(cur$rate_hr_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   TE3 = transfer_entropy(cur$pval_bp_diff, cur$rate_rsp_diff,type = 'quantiles',  lx = 3, ly = 3)
   
   trans_res_dbt_lag_2$a[i] = TE1$coef[1, 1]
   trans_res_dbt_lag_2$b[i] = TE1$coef[2, 1]
   trans_res_dbt_lag_2$c[i] = TE2$coef[1, 1]
   trans_res_dbt_lag_2$d[i] = TE2$coef[2, 1]
   trans_res_dbt_lag_2$e[i] = TE3$coef[1, 1]
   trans_res_dbt_lag_2$f[i] = TE3$coef[2, 1]
}

```









